### PR TITLE
Support testnet CL

### PR DESCRIPTION
**Pull request by zktaiga**

### CODE REVIEW

**Comment by heeckhau** [comment]
@zktaiga Looks good. Thanks!

**Comment by zktaiga** [comment]
> @zktaiga Looks good. Thanks!

Thanks. There's some frontend warning I want to iron out today before merging, I'll mark PR as ready when fixed.

**Comment by heeckhau** [comment]
@zktaiga Something went wrong building your PR.
I have applied your changes in the Atlas branch instead.

**Comment by heeckhau** [comment]
@zktaiga Something went wrong building your PR.
I have applied your changes in the Atlas branch instead.

**Pull request closed without merging**
